### ISSUE TITLE
Limit on files to process

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#335] opened 2021-08-20 18:00 UTC
# Story
_As an analyzer I want to limit the number of files processed so I can easily generate some test output_

# Assumptions
1. Add an argument to did that is interpreted by the DID finder 
`rucio://my-dataset&limit=5`

# Acceptance Criteria
1. How will we know when this story is complete

**Comment by gordonwatts** [comment] 2022-06-02 22:11
Duplicate of https://github.com/ssl-hep/ServiceX/issues/395.

**Closed as completed by gordonwatts** 2022-06-02 22:11 UTC
Labels: duplicate
