### ISSUE TITLE
Single-letter transform errors

### ISSUE THREAD

**Issue by alexander-held** [ssl-hep/ServiceX#408] opened 2022-04-27 14:36 UTC
**Describe the bug**
Transform failures report back a single-letter error.

**To Reproduce**
```python
from servicex import ServiceXDataset
from func_adl_servicex import ServiceXSourceUpROOT

dataset_opendata = "http://xrootd-local.unl.edu:1094//store/user/AGC/datasets/RunIIFall15MiniAODv2/TT_TuneCUETP8M1_13TeV-powheg-pythia8/MINIAODSIM//PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext3-v1/00000/00DF0A73-17C2-E511-B086-E41D2D08DE30.root"
sx_dataset = ServiceXDataset(dataset_opendata, backend_name='uproot')
ds = ServiceXSourceUpROOT(sx_dataset, "tree")
ds.Select(lambda e: {"electron_pt": e.electron_pt}).value()
```
results in
```
Transform 0d680f4a-b157-43c6-b9f8-ef7f1f43b296 had 1 errors:
  Error transforming file: h
  -> error.
```
with the full trace below.

environment: Python 3.9.12
```
func-adl-servicex    2.0
servicex             2.5
servicex-clients     1.2.2
```

**Expected behavior**
Informative error message describing what went wrong (in this case, the tree name: it is called "events" and not "tree").

**Screenshots**
n/a

**Additional context**
full trace:
```pytb
---------------------------------------------------------------------------
ServiceXFailedFileTransform               Traceback (most recent call last)
File [...]/lib/python3.9/site-packages/servicex/servicex.py:763, in ServiceXDataset._get_files(self, selection_query, data_type, notifier, title)
    762 # Reflect the files back up a level.
--> 763 async for r in stream_local_files:
    764     yield r

File [...]/lib/python3.9/site-packages/servicex/servicex.py:892, in ServiceXDataset._get_files_from_servicex(self, request_id, client, minio_adaptor, notifier)
    890 # Return the files to anyone that wants them!
--> 892 async for info in stream_downloaded:
    893     yield info

File [...]/lib/python3.9/site-packages/servicex/servicex.py:857, in ServiceXDataset._download_a_file(self, stream, request_id, minio_adaptor, notifier)
    856 file_object_list: List[Tuple[str, Path]] = []
--> 857 async for f in stream:
    858     copy_to_path = self._cache.data_file_location(request_id, f)

File [...]/lib/python3.9/site-packages/servicex/servicex.py:951, in ServiceXDataset._get_minio_bucket_files_from_servicex(self, request_id, client, minio_adaptor, notifier)
    950 # Return the minio information.
--> 951 async for info in stream_new_object:
    952     yield info

File [...]/lib/python3.9/site-packages/servicex/minio_adaptor.py:206, in find_new_bucket_files(adaptor, request_id, update)
    205 seen = []
--> 206 async for _ in update:
    207     # Sadly, this is blocking, and so may hold things up
    208     files = cast(List[str], adaptor.get_files(request_id))

File [...]/lib/python3.9/site-packages/servicex/utils.py:232, in stream_unique_updates_only(stream)
    231 last_p: Optional[TransformTuple] = None
--> 232 async for p in stream:
    233     if p != last_p:

File [...]/lib/python3.9/site-packages/servicex/servicex_adaptor.py:265, in trap_servicex_failures(stream)
    264 if did_fail is not None and did_fail != 0:
--> 265     raise ServiceXFailedFileTransform(
    266         f"ServiceX failed to transform {did_fail} "
    267         f"files - data incomplete (remaining: {remain}, "
    268         f"processed: {processed})."
    269     )
    271 yield p

ServiceXFailedFileTransform: (ServiceXFailedFileTransform(...), 'ServiceX failed to transform 1 files - data incomplete (remaining: 0, processed: 0).')

The above exception was the direct cause of the following exception:

ServiceXException                         Traceback (most recent call last)
Input In [9], in <cell line: 7>()
      5 sx_dataset = ServiceXDataset(dataset_opendata, backend_name='uproot')
      6 ds = ServiceXSourceUpROOT(sx_dataset, "tree")
----> 7 ds.Select(lambda e: {"electron_pt": e.electron_pt}).value()

File [...]/lib/python3.9/site-packages/make_it_sync/func_wrapper.py:63, in make_sync.<locals>.wrapped_call(*args, **kwargs)
     61 @wraps(fn)
     62 def wrapped_call(*args, **kwargs):
---> 63     return _sync_version_of_function(fn, *args, **kwargs)

File [...]/lib/python3.9/site-packages/make_it_sync/func_wrapper.py:26, in _sync_version_of_function(fn, *args, **kwargs)
     23 exector = ThreadPoolExecutor(max_workers=1)
     24 future = exector.submit(get_data_wrapper, *args, **kwargs)
---> 26 return future.result()

File [...]/lib/python3.9/concurrent/futures/_base.py:446, in Future.result(self, timeout)
    444     raise CancelledError()
    445 elif self._state == FINISHED:
--> 446     return self.__get_result()
    447 else:
    448     raise TimeoutError()

File [...]/lib/python3.9/concurrent/futures/_base.py:391, in Future.__get_result(self)
    389 if self._exception:
    390     try:
--> 391         raise self._exception
    392     finally:
    393         # Break a reference cycle with the exception in self._exception
    394         self = None

File [...]/lib/python3.9/concurrent/futures/thread.py:58, in _WorkItem.run(self)
     55     return
     57 try:
---> 58     result = self.fn(*self.args, **self.kwargs)
     59 except BaseException as exc:
     60     self.future.set_exception(exc)

File [...]/lib/python3.9/site-packages/make_it_sync/func_wrapper.py:21, in _sync_version_of_function.<locals>.get_data_wrapper(*args, **kwargs)
     19 asyncio.set_event_loop(loop)
     20 assert not loop.is_running()
---> 21 return loop.run_until_complete(fn(*args, **kwargs))

File [...]/lib/python3.9/asyncio/base_events.py:647, in BaseEventLoop.run_until_complete(self, future)
    644 if not future.done():
    645     raise RuntimeError('Event loop stopped before Future completed.')
--> 647 return future.result()

File [...]/lib/python3.9/site-packages/func_adl/object_stream.py:395, in ObjectStream.value_async(self, executor, title)
    392 # Run it
    393 from func_adl.ast.meta_data import remove_empty_metadata
--> 395 return await exe(remove_empty_metadata(self._q_ast), title)

File [...]/lib/python3.9/site-packages/func_adl_servicex/ServiceX.py:180, in ServiceXDatasetSourceBase.execute_result_async(self, a, title)
    178 # Run the query for real!
    179 attr = getattr(self._ds, name)
--> 180 result = await attr(q_str, title=title)
    182 # If this is a single column awkward query, and the user did not specify a column name, then
    183 # we will return the first column.
    184 if 'awkward' in name and (not has_col_names(a)) and 'key="col1"' in str(result.layout):

File [...]/lib/python3.9/site-packages/servicex/servicex_utils.py:51, in _wrap_in_memory_sx_cache.<locals>.cached_version_of_fn(*args, **kwargs)
     49 try:
     50     logger.debug(f"{h} - processing request")
---> 51     result = await fn(*args, **kwargs)
     52     sx._cache.set_inmem(h, result)
     53 finally:

File [...]/lib/python3.9/site-packages/servicex/servicex.py:360, in ServiceXDataset.get_data_parquet_async(self, selection_query, title)
    355 @functools.wraps(ServiceXABC.get_data_parquet_async, updated=())
    356 @_wrap_in_memory_sx_cache
    357 async def get_data_parquet_async(
    358     self, selection_query: str, title: Optional[str] = None
    359 ) -> List[Path]:
--> 360     return await self._file_return(selection_query, "parquet", title)

File [...]/lib/python3.9/site-packages/servicex/servicex.py:500, in ServiceXDataset._file_return(self, selection_query, data_format, title)
    497 async def convert_to_file(f: Path) -> Path:
    498     return f
--> 500 return await self._data_return(
    501     selection_query, convert_to_file, title, data_format
    502 )

File [...]/lib/python3.9/site-packages/backoff/_async.py:133, in retry_exception.<locals>.retry(*args, **kwargs)
    130 details = (target, args, kwargs, tries, elapsed)
    132 try:
--> 133     ret = await target(*args, **kwargs)
    134 except exception as e:
    135     giveup_result = await giveup(e)

File [...]/lib/python3.9/site-packages/backoff/_async.py:133, in retry_exception.<locals>.retry(*args, **kwargs)
    130 details = (target, args, kwargs, tries, elapsed)
    132 try:
--> 133     ret = await target(*args, **kwargs)
    134 except exception as e:
    135     giveup_result = await giveup(e)

File [...]/lib/python3.9/site-packages/servicex/servicex.py:621, in ServiceXDataset._data_return(self, selection_query, converter, title, data_format)
    587 @on_exception(backoff.constant, ServiceXUnknownRequestID, interval=0.1, max_tries=3)
    588 @on_exception(
    589     backoff.constant,
   (...)
    599     data_format: str = "root-file",
    600 ) -> List[Any]:
    601     """Given a query, return the data, in a unique order, that hold
    602     the data for the query.
    603 
   (...)
    619                             on the converter call.
    620     """
--> 621     all_data = {
    622         f.file: f.data
    623         async for f in self._stream_return(
    624             selection_query, title, converter, data_format
    625         )
    626     }
    628     # Finally, we need them in the proper order so we append them
    629     # all together
    630     ordered_data = [all_data[k] for k in sorted(all_data.keys())]

File [...]/lib/python3.9/site-packages/servicex/servicex.py:621, in <dictcomp>(.0)
    587 @on_exception(backoff.constant, ServiceXUnknownRequestID, interval=0.1, max_tries=3)
    588 @on_exception(
    589     backoff.constant,
   (...)
    599     data_format: str = "root-file",
    600 ) -> List[Any]:
    601     """Given a query, return the data, in a unique order, that hold
    602     the data for the query.
    603 
   (...)
    619                             on the converter call.
    620     """
--> 621     all_data = {
    622         f.file: f.data
    623         async for f in self._stream_return(
    624             selection_query, title, converter, data_format
    625         )
    626     }
    628     # Finally, we need them in the proper order so we append them
    629     # all together
    630     ordered_data = [all_data[k] for k in sorted(all_data.keys())]

File [...]/lib/python3.9/site-packages/servicex/servicex.py:664, in ServiceXDataset._stream_return(self, selection_query, title, converter, data_format)
    641 """Given a query, return the data, in the order it arrives back
    642 converted as appropriate.
    643 
   (...)
    657                         on the converter call.
    658 """
    659 as_data = (
    660     StreamInfoData(f.file, await asyncio.ensure_future(converter(f.path)))
    661     async for f in self._stream_local_files(selection_query, title, data_format)
    662 )  # type: ignore
--> 664 async for r in as_data:
    665     yield r

File [...]/lib/python3.9/site-packages/servicex/servicex.py:659, in <genexpr>(.0)
    634 async def _stream_return(
    635     self,
    636     selection_query: str,
   (...)
    639     data_format: str = "root-file",
    640 ) -> AsyncIterator[StreamInfoData]:
    641     """Given a query, return the data, in the order it arrives back
    642     converted as appropriate.
    643 
   (...)
    657                             on the converter call.
    658     """
--> 659     as_data = (
    660         StreamInfoData(f.file, await asyncio.ensure_future(converter(f.path)))
    661         async for f in self._stream_local_files(selection_query, title, data_format)
    662     )  # type: ignore
    664     async for r in as_data:
    665         yield r

File [...]/lib/python3.9/site-packages/servicex/servicex.py:699, in ServiceXDataset._stream_local_files(self, selection_query, title, data_format)
    691 # Get all the files
    692 as_files = (
    693     f
    694     async for f in self._get_files(
    695         selection_query, data_format, notifier, title
    696     )
    697 )  # type: ignore
--> 699 async for name, a_path in as_files:
    700     yield StreamInfoPath(name, Path(await a_path))

File [...]/lib/python3.9/site-packages/servicex/servicex.py:692, in <genexpr>(.0)
    689 notifier = self._create_notifier(title, True)
    691 # Get all the files
--> 692 as_files = (
    693     f
    694     async for f in self._get_files(
    695         selection_query, data_format, notifier, title
    696     )
    697 )  # type: ignore
    699 async for name, a_path in as_files:
    700     yield StreamInfoPath(name, Path(await a_path))

File [...]/lib/python3.9/site-packages/servicex/servicex.py:791, in ServiceXDataset._get_files(self, selection_query, data_type, notifier, title)
    789 self._cache.remove_query(query)
    790 await self._servicex_adaptor.dump_query_errors(client, request_id)
--> 791 raise ServiceXException(
    792     f"Failed to transform all files in {request_id}"
    793 ) from e

ServiceXException: (ServiceXException(...), 'Failed to transform all files in 0d680f4a-b157-43c6-b9f8-ef7f1f43b296')
```

**Comment by BenGalewsky** [comment] 2022-09-15 22:20
Fixed with [App PR 183](https://github.com/ssl-hep/ServiceX_App/pull/183), however this issue was just in the report of the file that generated the error. The cause is not being reported to ServiceX, so still not very useful. @masonproffitt  we need to make sure the uproot transformer reports something more than "error"

**Closed as completed** 2022-09-16 02:51 UTC
