### ISSUE TITLE
ServiceX not responding due to unavailable Rabbit MQ 

### ISSUE THREAD

**Issue by kyungeonchoi** [ssl-hep/ServiceX#272] opened 2021-03-29 09:31 UTC
**Describe the bug**
- ServiceX transformations are not running and just waiting for inputs. 
- Similar incident happened about a month ago due to the error in the rabbit MQ. 
- There is no error message. User cannot know whether it's running.

**Comment by BenGalewsky** [comment] 2021-03-29 14:14
I see this in the app log file
```
[2021-03-29 09:24:07,250] ERROR in rabbit_adaptor: Caught a channel error: (404, "NOT_FOUND - no exchange 'transformation_requests' in vhost '/'"), stopping...
Traceback (most recent call last):
  File "/home/servicex/servicex/rabbit_adaptor.py", line 183, in basic_publish
    mandatory=True)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2212, in basic_publish
    self._flush_output(self._message_confirmation_result.is_ready)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1340, in _flush_output
    raise self._closing_reason  # pylint: disable=E0702
pika.exceptions.ChannelClosedByBroker: (404, "NOT_FOUND - no exchange 'transformation_requests' in vhost '/'")
```

**Comment by BenGalewsky** [comment] 2021-03-29 14:21
It looks like this is caused by the RabbitMQ container being restarted by the cluster occasionally. We don't have persistence enabled, so the exchanges that are created at startup disappear.

I'll fix this by redeploying with persistence enabled

**Comment by gordonwatts** [comment] 2021-03-29 19:21
Why is the container restarted? Anything to worry about?

**Comment by BenGalewsky** [comment] 2021-05-12 16:20
This was fixed with https://github.com/ssl-hep/ServiceX_App/pull/96

**Closed as completed by BenGalewsky** 2021-05-12 16:20 UTC
